export const mockComics = [
  {
    id: "1",
    title: "Deadly Tales of the Gunslinger",
    issueNumber: "6",
    releaseDate: "April 2025",
    publisher: "Image Comics",
    credits: {
      writer: "John Doe",
      artist: "Jane Smith",
      colorist: "Sam Johnson",
      letterer: "Pat Williams",
      editor: "Alex Brown",
    },
    genre: ["Western", "Horror", "Action"],
    format: "Single Issue",
    country: "USA",
    synopsis:
      "The Gunslinger continues his dark journey through a haunted frontier. With supernatural forces closing in and a mysterious enemy pulling the strings, our anti-hero must confront his own demons while battling the monsters that plague the land.",
    coverImage: "/images/cover1.jpg",
  },
  {
    id: "2",
    title: "Spider-Man",
    issueNumber: "1",
    releaseDate: "April 16, 2025",
    publisher: "Marvel",
    credits: {
      writer: "J.M. DeMatteis",
      artist: "Mark Bagley",
      inker: "John Dell",
      colorist: "Jason Keith",
      letterer: "Joe Caramagna",
      editor: "Nick Lowe",
    },
    genre: ["Superhero", "Action", "Adventure"],
    format: "Single Issue",
    country: "USA",
    synopsis:
      "A new chapter begins for the web-slinger as he faces both new and familiar threats. With his personal life in turmoil and a city that needs him more than ever, Spider-Man must rise to the challenge.",
    coverImage: "/images/cover2.jpg",
  },
  {
    id: "3",
    title: "Gwenpool",
    issueNumber: "25",
    releaseDate: "April 16, 2025",
    publisher: "Marvel",
    credits: {
      writer: "Christopher Hastings",
      artist: "Gurihiru",
      letterer: "Clayton Cowles",
      editor: "Wil Moss",
    },
    genre: ["Comedy", "Action", "Superhero"],
    format: "Single Issue",
    country: "USA",
    synopsis:
      "Gwen Poole, the character who knows she's in a comic book, continues her meta adventures in the Marvel Universe. With her fourth-wall-breaking abilities and unpredictable nature, Gwenpool takes on challenges that no other hero would dare to face.",
    coverImage: "/images/cover3.jpg",
  },
  {
    id: "4",
    title: "Harley Quinn",
    issueNumber: "75",
    releaseDate: "April 16, 2025",
    publisher: "DC Comics",
    credits: {
      writer: "Stephanie Phillips",
      artist: "Riley Rossmo",
      colorist: "Ivan Plascencia",
      letterer: "Andworld Design",
      editor: "Katie Kubert",
    },
    genre: ["Action", "Comedy", "Crime"],
    format: "Single Issue",
    country: "USA",
    synopsis:
      "Harley Quinn's chaotic adventures continue as she navigates life in Gotham City. With her hyenas by her side and a smile on her face, Harley brings her unique brand of mayhem to every situation she encounters.",
    coverImage: "/images/cover4.jpg",
  },
  {
    id: "5",
    title: "Gwenpool Strikes Back",
    issueNumber: "3",
    releaseDate: "April 16, 2025",
    publisher: "Marvel",
    credits: {
      writer: "Leah Williams",
      artist: "David Baldeón",
      colorist: "Jesus Aburtov",
      letterer: "Joe Caramagna",
      editor: "Jordan D. White",
    },
    genre: ["Comedy", "Action", "Superhero"],
    format: "Single Issue",
    country: "USA",
    synopsis:
      "Gwenpool is back and more meta than ever! Determined to secure her place in the Marvel Universe, Gwen embarks on a series of increasingly outrageous schemes that put her on a collision course with the biggest heroes and villains around.",
    coverImage: "/images/cover5.jpg",
  },
  {
    id: "6",
    title: "Green Lantern: Fallen Hero",
    issueNumber: "1",
    releaseDate: "April 16, 2025",
    publisher: "DC Comics",
    credits: {
      writer: "Geoffrey Thorne",
      artist: "Tom Raney",
      colorist: "Michael Atiyeh",
      letterer: "Rob Leigh",
      editor: "Alex R. Carr",
    },
    genre: ["Superhero", "Sci-Fi", "Drama"],
    format: "Single Issue",
    country: "USA",
    synopsis:
      "The aftermath of a great battle leaves a hero's legacy in question. With only fragments of his power remaining and enemies closing in from all sides, a fallen Green Lantern must find the strength to rise again and face the challenges ahead.",
    coverImage: "/images/cover6.jpg",
  },
  {
    id: "7",
    title: "Invincible",
    issueNumber: "10",
    releaseDate: "April 16, 2025",
    publisher: "Image Comics",
    credits: {
      writer: "Robert Kirkman",
      artist: "Ryan Ottley",
      colorist: "Bill Crabtree",
      letterer: "Rus Wooton",
      editor: "Sean Mackiewicz",
    },
    genre: ["Superhero", "Action", "Drama"],
    format: "Single Issue",
    country: "USA",
    synopsis:
      "Mark Grayson continues his journey as Invincible, learning the ropes of being a superhero while dealing with the legacy of his father. New threats emerge as he struggles to balance his personal life with his heroic responsibilities.",
    coverImage: "/images/cover7.jpg",
  },
  {
    id: "8",
    title: "Dandadan",
    issueNumber: "1",
    releaseDate: "April 16, 2025",
    publisher: "Viz Media",
    credits: {
      writer: "Yukinobu Tatsu",
      artist: "Yukinobu Tatsu",
      translator: "John Werry",
      editor: "Alexis Kirsch",
    },
    genre: ["Supernatural", "Action", "Comedy"],
    format: "Manga",
    country: "Japan",
    synopsis:
      "When Momo Ayase and Ken Takakura meet, they form an unlikely alliance to battle supernatural threats. With Momo's ability to see ghosts and Ken's connection to aliens, they embark on a bizarre adventure that blends the paranormal with science fiction.",
    coverImage: "/images/cover8.jpg",
  },
]
